# 
# Do not Edit! Generated by:
# spectacle version 0.13
# 
# >> macros
%define snap 20090923
# << macros

Name:       libedit
Summary:    The NetBSD Editline library
Version:    3.0_snap20090923
Release:    1
Group:      System/Libraries
License:    BSD
URL:        http://www.thrysoee.dk/editline/
Source0:    http://www.thrysoee.dk/editline/%{name}-20090923-3.0.tar.gz
Source100:  libedit.yaml
Patch0:     tgetent.patch
Requires(post):  /sbin/ldconfig
Requires(postun):  /sbin/ldconfig
BuildRequires:  pkgconfig(ncurses)
BuildRequires:  gawk

BuildRoot:  %{_tmppath}/%{name}-%{version}-build

%description
Libedit is an autotool- and libtoolized port of the NetBSD Editline library.
It provides generic line editing, history, and tokenization functions, similar
to those found in GNU Readline.



%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   ncurses-devel

%description devel
This package contains development files for %{name}.


%prep
%setup -q -n %{name}-20090923-3.0

# tgetent.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
autoreconf -f -i
# << build pre

%configure --disable-static
# Call make instruction with smp support
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre

# << install pre
%make_install

# >> install post
find $RPM_BUILD_ROOT -type f -name "*.la" -delete


# << install post

%clean
rm -rf %{buildroot}



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig



%files
%defattr(-,root,root,-)
# >> files
%doc ChangeLog COPYING THANKS
%{_libdir}/%{name}.so.*
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%doc examples/fileman.c examples/test.c
%doc %{_mandir}/man3/*
%doc %{_mandir}/man5/editrc.5*
%{_includedir}/histedit.h
%{_libdir}/%{name}.so
%{_libdir}/pkgconfig/%{name}.pc
%dir %{_includedir}/editline
%{_includedir}/editline/readline.h
# << files devel

